#!/bin/bash

set -e
set -o pipefail

if hash service 2> /dev/null; then
    service bcccore stop || echo "bcccore wasn't running!"
elif hash stop 2> /dev/null; then
    stop "$service_name" || echo "bcccore wasn't running!"
elif hash systemctl 2> /dev/null; then
    systemctl disable "bcccore.service" || echo "bcccore wasn't running!"
else
    echo "Your system does not appear to use upstart or systemd, so bcccore could not be stopped"
fi
